version: "3.5"

services:
  quarkus-service:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    image: quarkus/quarkus-demo-jvm:latest
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://quarkus-db:5432/simplechat

    ports:
      - "8080:8080"  # the HTTP endpoint
    networks:
      - quarkus 
    depends_on:
      - quarkus-db

  quarkus-db:
    image: "postgres:10.5"
    environment:
      - POSTGRES_DB=simplechat   # quarkus
      - POSTGRES_USER=sc_admin
      - POSTGRES_PASSWORD=sc_admin
    volumes:
              - "./pgdata:/var/lib/postgresql/data"    

    ports:
      - "5432:5432"
    networks:
      - quarkus
      
networks:
   quarkus:
    driver: bridge

