apiVersion: apps/v1
kind: Deployment
metadata:
  name: thomas-service
  labels:
    app: thomas-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thomas-service
  template:
    metadata:
      labels:
        app: thomas-service
        io.kompose.network/thomas: "true"
    spec:
      containers:
      - name: thomas-service
        image: public.ecr.aws/e8v6d9d7/thomas-demo-jvm:1.0.0 # quarkus-demo-jvm:1.0.0 # sha256:76bd2f142864206b3a862a006b1d89d28e13973341004e6fb58a010342c62abd  # cgs/quarkus-demo-jvm:latest
        ports:
         - containerPort: 8080
        env:
        - name: USER_NAME
          valueFrom:
            secretKeyRef:
              name: quarkus-db-secret
              key: postgres-user
        - name: USER_PWD
          valueFrom:
            secretKeyRef:
              name: thomas-quarkus-db-secret
              key: postgres-password
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: thomas-quarkus-demo-config
              key: quarkus-demo-url
        #- name: QUARKUS_DATASOURCE_JDBC_URL
        #   value: jdbc:postgresql://quarkus-db:5432/simplechat
---
apiVersion: v1
kind: Service
metadata:
  name: thomas-service
  labels:
    app: thomas-service
spec:
  type: LoadBalancer  # NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30168  # must be between 30000 and 32767
  selector:
    app: thomas-service


